Repository worldcoin/iris-mpc, pull requests merged in 2024-12, with the labels that each got.

#731 load db chunks from s3
  Cargo.lock
  Cargo.toml
  deploy/stage/common-values-iris-mpc.yaml
  deploy/stage/smpcv2-0-stage/values-iris-mpc.yaml
  deploy/stage/smpcv2-1-stage/values-iris-mpc.yaml
  deploy/stage/smpcv2-2-stage/values-iris-mpc.yaml
  iris-mpc-common/src/config/mod.rs
  iris-mpc-store/Cargo.toml
  iris-mpc-store/src/lib.rs
  iris-mpc-store/src/s3_importer.rs
  iris-mpc/src/bin/server.rs
Labels: enhancement

#767 Update Hawk Pack dependency and Python bindings
  Cargo.lock
  Cargo.toml
  iris-mpc-cpu/benches/hnsw.rs
  iris-mpc-cpu/examples/hnsw-ex.rs
  iris-mpc-cpu/src/hawkers/galois_store.rs
  iris-mpc-cpu/src/hawkers/plaintext_store.rs
  iris-mpc-cpu/src/network/grpc.rs
  iris-mpc-cpu/src/py_bindings/hnsw.rs
  iris-mpc-py/README.md
  iris-mpc-py/examples-py/test_integration.py
  iris-mpc-py/src/py_hnsw/pyclasses/hawk_searcher.rs
Labels: chore

#782 fix: also ignore supermatchers for in-memory
  iris-mpc-gpu/src/server/actor.rs
Labels: patch

#785 [POP-1990] add e2e values for iris-mpc
  deploy/e2e/iris-mpc-0.yaml.tpl
  deploy/e2e/iris-mpc-1.yaml.tpl
  deploy/e2e/iris-mpc-2.yaml.tpl
Labels: enhancement

#799 filter out supermatchers on partial results
  iris-mpc-gpu/src/dot/distance_comparator.rs
  iris-mpc-gpu/src/server/actor.rs
Labels: patch

#812 template variables to avoid name clashes
  deploy/e2e/iris-mpc-0.yaml.tpl
  deploy/e2e/iris-mpc-1.yaml.tpl
  deploy/e2e/iris-mpc-2.yaml.tpl
Labels: patch

#823 turn off exporter
  deploy/prod/smpcv2-0-prod/values-iris-mpc.yaml
  deploy/prod/smpcv2-1-prod/values-iris-mpc.yaml
  deploy/prod/smpcv2-2-prod/values-iris-mpc.yaml
Labels: patch

#825 enable importer
  deploy/prod/smpcv2-0-prod/values-iris-mpc.yaml
  deploy/prod/smpcv2-1-prod/values-iris-mpc.yaml
  deploy/prod/smpcv2-2-prod/values-iris-mpc.yaml
Labels: patch

#824 prefetch the next chunk to gpu mem manually
  iris-mpc-gpu/src/dot/share_db.rs
  iris-mpc-gpu/src/helpers/mod.rs
  iris-mpc-gpu/src/helpers/query_processor.rs
  iris-mpc-gpu/src/server/actor.rs
Labels: enhancement

#803 async read chunk
  iris-mpc-store/src/s3_importer.rs
Labels: enhancement

#832 chore: Use the 16k bucket
  deploy/prod/smpcv2-0-prod/values-iris-mpc.yaml
  deploy/prod/smpcv2-1-prod/values-iris-mpc.yaml
  deploy/prod/smpcv2-2-prod/values-iris-mpc.yaml
Labels: patch

#835 fix: log throughput correctly
  iris-mpc-store/src/s3_importer.rs
Labels: patch

#829 measure prefetch time
  iris-mpc-gpu/src/server/actor.rs
Labels: enhancement

#845 Update stage version to include last modified fix
  deploy/stage/common-values-iris-mpc.yaml
Labels: patch

#846 load chunk in smaller ranges
  .github/workflows/temp-branch-build-and-push.yaml
  deploy/stage/common-values-iris-mpc.yaml
  deploy/stage/smpcv2-0-stage/values-iris-mpc.yaml
  deploy/stage/smpcv2-1-stage/values-iris-mpc.yaml
  deploy/stage/smpcv2-2-stage/values-iris-mpc.yaml
  iris-mpc-store/src/s3_importer.rs
Labels: enhancement

#858 generate keys on startup for e2es
  deploy/e2e/iris-mpc-0.yaml.tpl
  deploy/e2e/iris-mpc-1.yaml.tpl
  deploy/e2e/iris-mpc-2.yaml.tpl
Labels: enhancement

#859 fix apt command
  Dockerfile.nocuda
  deploy/e2e/iris-mpc-0.yaml.tpl
  deploy/e2e/iris-mpc-1.yaml.tpl
  deploy/e2e/iris-mpc-2.yaml.tpl
Labels: patch

#862 configurable region for key-manager
  deploy/e2e/iris-mpc-0.yaml.tpl
  deploy/e2e/iris-mpc-1.yaml.tpl
  deploy/e2e/iris-mpc-2.yaml.tpl
  iris-mpc-common/src/bin/README.md
  iris-mpc-common/src/bin/key_manager.rs
Labels: patch, chore

#864 use custom aws endpoint
  deploy/e2e/iris-mpc-0.yaml.tpl
  deploy/e2e/iris-mpc-1.yaml.tpl
  deploy/e2e/iris-mpc-2.yaml.tpl
  iris-mpc-common/src/bin/key_manager.rs
Labels: patch
