Repository worldcoin/iris-mpc, pull requests merged in 2024-11, with the labels that each got.

#641 Ps/fix/log durations
  deploy/prod/common-values-iris-mpc.yaml
  deploy/prod/smpcv2-0-prod/values-iris-mpc.yaml
  deploy/prod/smpcv2-1-prod/values-iris-mpc.yaml
  deploy/prod/smpcv2-2-prod/values-iris-mpc.yaml
  iris-mpc-gpu/src/server/actor.rs
Labels: patch

#646 fix config
  deploy/prod/smpcv2-0-prod/values-iris-mpc.yaml
  deploy/prod/smpcv2-1-prod/values-iris-mpc.yaml
  deploy/prod/smpcv2-2-prod/values-iris-mpc.yaml
Labels: patch

#644 preprocess limbs earlier
  iris-mpc-gpu/src/server/actor.rs
  iris-mpc-gpu/src/server/mod.rs
  iris-mpc-gpu/tests/e2e.rs
  iris-mpc/src/bin/server.rs
Labels: enhancement

#657 don't count dropped message in batch
  iris-mpc/src/bin/server.rs
Labels: patch

#658 more metrics and heartbeat log
  iris-mpc-gpu/src/server/actor.rs
  iris-mpc/src/bin/server.rs
Labels: enhancement

#663 more robust handling of sequence id
  deploy/stage/common-values-iris-mpc.yaml
  iris-mpc-store/src/lib.rs
  iris-mpc/src/bin/server.rs
Labels: enhancement

#685 fix the invalid transformation from < to <= in the threshold check
  iris-mpc-gpu/src/threshold_ring/cuda/kernel.cu
  iris-mpc-gpu/tests/e2e.rs
Labels: patch

#690 Return in-batch matching request ids
  iris-mpc-common/src/helpers/smpc_request.rs
  iris-mpc-gpu/src/dot/kernel.cu
  iris-mpc-gpu/src/server/actor.rs
  iris-mpc-gpu/src/server/mod.rs
  iris-mpc-gpu/tests/e2e.rs
  iris-mpc-store/src/lib.rs
  iris-mpc/src/bin/server.rs
Labels: enhancement

#695 filter out matches outside batchsize
  iris-mpc-gpu/src/server/actor.rs
Labels: patch

#700 destroy cuda events
  iris-mpc-gpu/src/helpers/device_manager.rs
  iris-mpc-gpu/src/server/actor.rs
Labels: enhancement

#701 metric about used and free gpu memory
  iris-mpc-gpu/src/server/actor.rs
Labels: enhancement

#702 manually manage serial id
  iris-mpc-store/migrations/20241121084719_remove_sequence.sql
  iris-mpc-store/src/lib.rs
  iris-mpc-upgrade/src/bin/tcp_upgrade_server.rs
  iris-mpc-upgrade/src/lib.rs
  iris-mpc/src/bin/server.rs
Labels: enhancement

#684 Add a ReSharing protocol to both re-share to existing parties and create shares for additional parties
  .github/workflows/build-all-targets.yml
  .github/workflows/doc.yml
  .github/workflows/lint-clippy.yaml
  .github/workflows/run-unit-tests.yaml
  .github/workflows/test-gpu.yaml
  Cargo.lock
  Dockerfile
  Dockerfile.base
  Dockerfile.debug
  Dockerfile.nccl
  Dockerfile.nocuda
  Dockerfile.shares-encoding
  deploy/stage/common-values-reshare-server.yaml
  deploy/stage/smpcv2-1-stage/values-reshare-server.yaml
  iris-mpc-common/src/galois.rs
  iris-mpc-common/src/galois_engine.rs
  iris-mpc-store/src/lib.rs
  iris-mpc-upgrade/Cargo.toml
  iris-mpc-upgrade/build.rs
  iris-mpc-upgrade/protos/reshare.proto
  iris-mpc-upgrade/src/bin/.gitignore
  iris-mpc-upgrade/src/bin/README.md
  iris-mpc-upgrade/src/bin/docker-compose.yaml
  iris-mpc-upgrade/src/bin/reshare-client.rs
  iris-mpc-upgrade/src/bin/reshare-protocol-local.sh
  iris-mpc-upgrade/src/bin/reshare-server.rs
  iris-mpc-upgrade/src/bin/seed_v2_dbs.rs
  iris-mpc-upgrade/src/config.rs
  iris-mpc-upgrade/src/lib.rs
  iris-mpc-upgrade/src/proto/iris_mpc_reshare.rs
  iris-mpc-upgrade/src/proto/mod.rs
  iris-mpc-upgrade/src/reshare.rs
Labels: chore

#708 fix batch matches
  iris-mpc-gpu/src/dot/distance_comparator.rs
  iris-mpc-gpu/src/dot/kernel.cu
Labels: patch

#718 fix typo nginx config
  deploy/stage/common-values-reshare-server.yaml
Labels: patch

#719 separate live and health check
  Cargo.lock
  deploy/prod/common-values-iris-mpc.yaml
  deploy/prod/smpcv2-0-prod/values-iris-mpc.yaml
  deploy/prod/smpcv2-1-prod/values-iris-mpc.yaml
  deploy/prod/smpcv2-2-prod/values-iris-mpc.yaml
  deploy/stage/common-values-iris-mpc.yaml
  iris-mpc-common/src/config/mod.rs
  iris-mpc/src/bin/server.rs
Labels: enhancement

#720 bump to latest
  deploy/stage/common-values-iris-mpc.yaml
  deploy/stage/common-values-reshare-server.yaml
  deploy/stage/common-values-upgrade-server-left.yaml
  deploy/stage/common-values-upgrade-server-right.yaml
Labels: patch

#723 configurable healtcheck server
  deploy/stage/smpcv2-1-stage/values-reshare-server.yaml
  iris-mpc-upgrade/src/bin/reshare-server.rs
  iris-mpc-upgrade/src/bin/tcp_upgrade_server.rs
  iris-mpc-upgrade/src/config.rs
  iris-mpc-upgrade/src/reshare.rs
  iris-mpc-upgrade/src/utils.rs
Labels: patch
