Repository worldcoin/iris-mpc, pull requests merged in 2025-05, with the labels that each got.

#1302 Fix/use config for batch size override
  .test.env
  deploy/stage/ampc-hnsw-0-stage/values-ampc-hnsw.yaml
  deploy/stage/ampc-hnsw-1-stage/values-ampc-hnsw.yaml
  deploy/stage/ampc-hnsw-2-stage/values-ampc-hnsw.yaml
  iris-mpc-common/src/config/mod.rs
  iris-mpc/src/services/processors/batch.rs
Labels: patch

#1279 Update init-test-dbs binary to improve usability
  iris-mpc-cpu/bin/init_test_dbs.rs
Labels: enhancement

#1320 Fix logging leftover
  iris-mpc-gpu/src/server/actor.rs
Labels: patch

#1321 Fix: Add missing args to HawkArgs in hawk upgrade binary
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
Labels: patch

#1322 Fix running genesis locally
  Cargo.lock
  Dockerfile.genesis.dev.hawk
  README.md
  docker-compose.test.genesis.yaml
  scripts/run-server-docker.sh
Labels: patch, chore

#1299 use `eyre::bail!` macro and `eyre::Result` consistently
  iris-mpc-common/src/bin/key_manager.rs
  iris-mpc-common/src/config/mod.rs
  iris-mpc-common/src/galois_engine.rs
  iris-mpc-common/src/helpers/aws.rs
  iris-mpc-common/src/helpers/aws_sigv4.rs
  iris-mpc-common/src/helpers/kms_dh.rs
  iris-mpc-common/src/helpers/sqs.rs
  iris-mpc-common/src/helpers/sync.rs
  iris-mpc-common/src/iris_db/iris.rs
  iris-mpc-common/src/server_coordination.rs
  iris-mpc-common/src/tracing.rs
  iris-mpc-cpu/src/execution/hawk_main/state_check.rs
  iris-mpc-cpu/src/hawkers/aby3/test_utils.rs
  iris-mpc-cpu/src/hawkers/plaintext_store.rs
  iris-mpc-cpu/src/hnsw/searcher.rs
  iris-mpc-cpu/src/network/grpc.rs
  iris-mpc-cpu/src/network/value.rs
  iris-mpc-cpu/src/protocol/binary.rs
  iris-mpc-cpu/src/protocol/ops.rs
  iris-mpc-gpu/src/bin/nccl.rs
  iris-mpc-gpu/src/helpers/device_manager.rs
  iris-mpc-gpu/src/helpers/query_processor.rs
  iris-mpc-gpu/src/server/actor.rs
  iris-mpc-gpu/tests/bitinject.rs
  iris-mpc-gpu/tests/bucket_threshold.rs
  iris-mpc-gpu/tests/buckets.rs
  iris-mpc-gpu/tests/extract_msb_mod.rs
  iris-mpc-gpu/tests/lift.rs
  iris-mpc-gpu/tests/one_bucket.rs
  iris-mpc-gpu/tests/threshold.rs
  iris-mpc-gpu/tests/threshold_and_or_tree.rs
  iris-mpc-store/src/lib.rs
  iris-mpc-store/src/s3_importer.rs
  iris-mpc-upgrade-hawk/bin/iris_mpc_hawk_genesis.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
  iris-mpc-upgrade/src/bin/reshare-client.rs
  iris-mpc-upgrade/src/bin/reshare-server.rs
  iris-mpc-upgrade/src/bin/seed_v2_dbs.rs
  iris-mpc-upgrade/src/reshare.rs
  iris-mpc-upgrade/src/utils.rs
  iris-mpc/bin/client/client.rs
  iris-mpc/bin/server.rs
  iris-mpc/bin/server/iris_mpc_hawk.rs
  iris-mpc/src/client/e2e.rs
  iris-mpc/src/client/iris_data.rs
  iris-mpc/src/server/mod.rs
  iris-mpc/src/services/init/mod.rs
  iris-mpc/src/services/processors/batch.rs
  iris-mpc/src/services/processors/job.rs
  iris-mpc/src/services/processors/mod.rs
  iris-mpc/src/services/store/mod.rs
Labels: chore

#1325 Add S3 local setup functionality
  README.md
  docker-compose.test.genesis.yaml
  iris-mpc-cpu/src/genesis/batch_generator.rs
  iris-mpc-cpu/src/genesis/utils/constants.rs
  iris-mpc-cpu/src/genesis/utils/fetcher.rs
  iris-mpc-cpu/src/genesis/utils/mod.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
  scripts/tools/init-localstack.sh
Labels: chore

#1303 fix: introduce separate bucket recv buffer
  iris-mpc-gpu/src/server/actor.rs
  iris-mpc-gpu/src/threshold_ring/protocol.rs
  iris-mpc-gpu/tests/bitinject.rs
  iris-mpc-gpu/tests/bucket_threshold.rs
  iris-mpc-gpu/tests/buckets.rs
  iris-mpc-gpu/tests/extract_msb_mod.rs
  iris-mpc-gpu/tests/lift.rs
  iris-mpc-gpu/tests/one_bucket.rs
  iris-mpc-gpu/tests/threshold.rs
  iris-mpc-gpu/tests/threshold_and_or_tree.rs
Labels: patch

#1333 aurel/fix-intra-logic: Emulate the behavior of inserting entries one-by-one
  iris-mpc-cpu/src/execution/hawk_main/matching.rs
Labels: patch

#1342 add mirrored shares to batch query
  .github/workflows/cpu-integration-tests.yaml
  iris-mpc-common/src/galois_engine.rs
  iris-mpc-cpu/src/execution/hawk_main.rs
  iris-mpc-cpu/src/protocol/shared_iris.rs
  iris-mpc/src/services/processors/batch.rs
  iris-mpc/src/services/processors/mod.rs
Labels: patch

#1347 fix: don't flip imaginary share in mask
  iris-mpc-common/src/galois_engine.rs
  iris-mpc-common/src/test.rs
  iris-mpc-cpu/src/protocol/shared_iris.rs
  iris-mpc/bin/server.rs
  iris-mpc/src/services/processors/mod.rs
Labels: patch

#1329 HNSW Genesis :: Fix regression
  iris-mpc-common/src/config/mod.rs
  iris-mpc-common/src/lib.rs
  iris-mpc-common/src/vector_id.rs
  iris-mpc-cpu/src/genesis/batch_generator.rs
  iris-mpc-cpu/src/genesis/hawk_handle.rs
  iris-mpc-cpu/src/genesis/hawk_job.rs
  iris-mpc-cpu/src/genesis/mod.rs
  iris-mpc-cpu/src/genesis/utils/errors.rs
  iris-mpc-cpu/src/genesis/utils/fetcher.rs
  iris-mpc-cpu/src/genesis/utils/logger.rs
  iris-mpc-cpu/src/genesis/utils/mod.rs
  iris-mpc-cpu/src/genesis/utils/types.rs
  iris-mpc-store/src/lib.rs
  iris-mpc-upgrade-hawk/bin/iris_mpc_hawk_genesis.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
  scripts/tools/init-localstack.sh
Labels: enhancement, patch

#1356 Implement genesis graph insertion logic
  iris-mpc-cpu/src/execution/hawk_main.rs
  iris-mpc-cpu/src/execution/hawk_main/insert.rs
  iris-mpc-cpu/src/execution/hawk_main/search.rs
  iris-mpc-cpu/src/genesis/hawk_handle.rs
  iris-mpc-cpu/src/genesis/hawk_job.rs
  iris-mpc-cpu/src/hawkers/aby3/aby3_store.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
Labels: enhancement

#1357 HNSW Genesis: Various minor improvements
  iris-mpc-cpu/src/genesis/batch_generator.rs
  iris-mpc-cpu/src/genesis/hawk_handle.rs
  iris-mpc-cpu/src/genesis/hawk_job.rs
  iris-mpc-cpu/src/genesis/mod.rs
  iris-mpc-cpu/src/genesis/state_accessor.rs
  iris-mpc-cpu/src/genesis/utils/errors.rs
  iris-mpc-cpu/src/genesis/utils/logger.rs
  iris-mpc-cpu/src/genesis/utils/mod.rs
  iris-mpc-upgrade-hawk/bin/iris_mpc_hawk_genesis.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
Labels: enhancement

#1367 Implement database persistence for genesis indexer
  iris-mpc-cpu/src/genesis/batch_generator.rs
  iris-mpc-cpu/src/genesis/hawk_handle.rs
  iris-mpc-cpu/src/genesis/hawk_job.rs
  iris-mpc-cpu/src/genesis/mod.rs
  iris-mpc-cpu/src/genesis/state_accessor.rs
  iris-mpc-cpu/src/genesis/sync.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
Labels: enhancement

#1375 HNSW-Genesis: Minor Refactors
  iris-mpc-cpu/src/genesis/batch_generator.rs
  iris-mpc-cpu/src/genesis/hawk_handle.rs
  iris-mpc-cpu/src/genesis/hawk_job.rs
  iris-mpc-cpu/src/genesis/mod.rs
  iris-mpc-cpu/src/genesis/state_sync.rs
  iris-mpc-cpu/src/genesis/utils/errors.rs
  iris-mpc-cpu/src/genesis/utils/logger.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
Labels: enhancement

#1377 Fix/anon stats session
  .github/workflows/temp-branch-build-and-push-hawk.yaml
  iris-mpc-cpu/src/execution/hawk_main.rs
  iris-mpc-cpu/src/protocol/ops.rs
Labels: patch

#1384 fix local script + bonus logging
  iris-mpc-cpu/src/execution/hawk_main.rs
  scripts/run-server.sh
Labels: patch

#1386 Fix purge DB script
  scripts/purge_stage/purge_stage_dbs.sh
Labels: patch

#1392 Add local setup for Genesis
  README.md
  docker-compose.test.genesis.yaml
  iris-mpc-cpu/bin/init_test_dbs.rs
  scripts/tools/init_db_from_plaintext_iris_file.sh
Labels: chore

#1366 [POP-2506] Alternate full scan side per batch
  iris-mpc-gpu/src/server/actor.rs
Labels: codex

#1385 HAWK-Genesis: Further minor refactors
  iris-mpc-common/src/postgres/mod.rs
  iris-mpc-cpu/src/execution/hawk_main.rs
  iris-mpc-cpu/src/genesis/batch_generator.rs
  iris-mpc-cpu/src/genesis/hawk_handle.rs
  iris-mpc-cpu/src/genesis/hawk_job.rs
  iris-mpc-cpu/src/genesis/mod.rs
  iris-mpc-cpu/src/genesis/state_accessor.rs
  iris-mpc-cpu/src/genesis/state_sync.rs
  iris-mpc-cpu/src/genesis/utils/mod.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
Labels: enhancement

#1397 fix: build script for iris-mpc upgrade no longer always invalidates generated sources
  iris-mpc-upgrade/build.rs
Labels: patch

#1393 Add better logging
  .github/workflows/temp-branch-build-and-push-upgrade-hawk.yaml
  README.md
  iris-mpc-upgrade-hawk/bin/iris_mpc_hawk_genesis.rs
Labels: chore

#1406 better logging / visibility / fix deadlock in e2e
  iris-mpc/src/client/e2e.rs
Labels: patch

#1405 Add modifications table usage for the Delta part of Genesis
  iris-mpc-cpu/src/genesis/mod.rs
  iris-mpc-cpu/src/genesis/state_accessor.rs
  iris-mpc-cpu/src/genesis/state_sync.rs
  iris-mpc-cpu/src/genesis/utils/errors.rs
  iris-mpc-store/src/lib.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
Labels: enhancement
