Repository worldcoin/iris-mpc, pull requests merged in 2025-02, with the labels that each got.

#996 Fix OOB: use max batch size
  iris-mpc-gpu/src/server/actor.rs
Labels: patch

#999 Fix non-deterministic buckets
  iris-mpc-common/src/config/mod.rs
  iris-mpc-gpu/src/server/actor.rs
  iris-mpc-gpu/tests/e2e.rs
  iris-mpc/src/bin/server.rs
Labels: patch

#948 [POP-2033] config and initial impl for LUC enablement
  iris-mpc-common/src/config/mod.rs
  iris-mpc-common/src/helpers/smpc_request.rs
  iris-mpc-common/tests/smpc_request.rs
  iris-mpc-gpu/src/server/actor.rs
  iris-mpc-gpu/src/server/mod.rs
  iris-mpc-gpu/tests/or_policy.rs
  iris-mpc/src/bin/client.rs
  iris-mpc/src/bin/server.rs
Labels: enhancement

#1004 feat: fix check_bucket_statistics and disable faulty WithOrRuleSet testcases in e2e
  iris-mpc-gpu/src/dot/distance_comparator.rs
  iris-mpc-gpu/src/dot/kernel.cu
  iris-mpc-gpu/tests/e2e.rs
Labels: patch

#986 Fix NCCL/EFA of base docker image for smaller images
  .github/workflows/temp-branch-build-and-push.yaml
  Dockerfile
  Dockerfile.base
Labels: patch

#1023 Aurel/server hawk
  .dockerignore
  .test.env
  Cargo.lock
  Cargo.toml
  Dockerfile.hawk
  README.md
  docker-compose.yml
  iris-mpc-common/src/config/mod.rs
  iris-mpc-common/src/helpers/statistics.rs
  iris-mpc-common/src/job.rs
  iris-mpc-cpu/src/database_generators.rs
  iris-mpc-cpu/src/execution/hawk_main.rs
  iris-mpc/Cargo.toml
  iris-mpc/src/bin/client.rs
  iris-mpc/src/bin/server_hawk.rs
  scripts/init-db.sh
  scripts/init-localstack.sh
  scripts/init-servers.sh
  scripts/run-client.sh
  scripts/run-server-docker.sh
  scripts/run-server.sh
Labels: chore

#1029 fix: use env variables when arguments are not passed
  scripts/reshare-client.sh
Labels: patch

#1032 fix: use parameter --ca-root-file-path
  scripts/reshare-client.sh
Labels: patch

#1040 send populated modifications to actor
  .github/workflows/temp-branch-build-and-push.yaml
  deploy/stage/common-values-iris-mpc.yaml
  iris-mpc/src/bin/server.rs
Labels: patch

#1050 fix: reshare-client.sh should use different numbering when choosing reshare-server domain
  scripts/reshare-client.sh
Labels: patch

#1055 Hawk docker updates
  Dockerfile.dev.hawk
  Dockerfile.hawk
  docker-compose.dev.yaml
  scripts/init-db-pgres.sql
  scripts/init-db.sh
Labels: enhancement

#1058 Fix/client send correct requests
  .github/workflows/cpu-integration-tests.yaml
  .test.env
  Cargo.lock
  iris-mpc-common/src/helpers/sqs_s3_helper.rs
  iris-mpc/Cargo.toml
  iris-mpc/bin/client.rs
  iris-mpc/bin/server.rs
  iris-mpc/bin/server_hawk.rs
  iris-mpc/src/client.rs
  iris-mpc/src/lib.rs
  scripts/run-client.sh
Labels: patch

#1057 Hawk mode config extensions
  .test.env
  iris-mpc-common/src/config/mod.rs
  iris-mpc/bin/server.rs
  iris-mpc/bin/server_hawk.rs
  scripts/run-server.sh
Labels: enhancement

#1061 missing bin target
  iris-mpc/Cargo.toml
Labels: patch

#1064 Chore/docs for server hnsw [POP-2209]
  README.md
  iris-mpc-common/src/helpers/statistics.rs
  iris-mpc-common/src/job.rs
Labels: chore

#1056 aurel/fix-plans-order: Decouple set_entry_point and set_links
  iris-mpc-cpu/src/execution/hawk_main.rs
  iris-mpc-cpu/src/hnsw/graph/layered_graph.rs
Labels: patch

#1053 Implement batch insertions for HNSW sorted lists
  iris-mpc-cpu/src/hnsw/graph/neighborhood.rs
  iris-mpc-cpu/src/hnsw/mod.rs
  iris-mpc-cpu/src/hnsw/sorting/batcher.rs
  iris-mpc-cpu/src/hnsw/sorting/mod.rs
  iris-mpc-cpu/src/hnsw/sorting/sorting_network.rs
  iris-mpc-cpu/src/hnsw/vector_store.rs
Labels: enhancement

#1068 aurel/fix-hawk-request: Increase stack size for integration tests [POP-2168]
  .test.env
  iris-mpc-cpu/src/execution/hawk_main.rs
  iris-mpc-cpu/src/hawkers/aby3_store.rs
  iris-mpc/bin/server_hawk.rs
  iris-mpc/src/client.rs
  scripts/init-localstack.sh
  scripts/run-server-docker.sh
  scripts/run-server.sh
Labels: patch

#1074 [POP-1991] Fix e2e aws configuration
  iris-mpc/bin/server.rs
Labels: patch

#1076 Fix HNSW local setup
  scripts/run-client-docker.sh
  scripts/run-client.sh
Labels: patch
