Repository worldcoin/iris-mpc, pull requests merged in 2025-07, with the labels that each got.

#1486 Update purge stage dbs script
  scripts/purge_stage/README.md
  scripts/purge_stage/delete_mongodb_cpu_collections.sh
  scripts/purge_stage/delete_mongodb_gpu_collections.sh
  scripts/purge_stage/purge_stage_dbs.sh
Labels: chore

#1485 Fix saving prev modification
  iris-mpc-cpu/src/genesis/state_accessor.rs
  iris-mpc-cpu/src/genesis/state_sync.rs
  iris-mpc-store/src/lib.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
Labels: patch

#1489 Fix last persisted delta modification to always be stored
  .github/workflows/temp-branch-build-and-push-upgrade-hawk.yaml
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
Labels: patch

#1478 Add TLS capability to the networking stack
  Cargo.lock
  iris-mpc-common/src/config/mod.rs
  iris-mpc-cpu/Cargo.toml
  iris-mpc-cpu/benches/networking.rs
  iris-mpc-cpu/src/execution/hawk_main.rs
  iris-mpc-cpu/src/network/tcp/README.md
  iris-mpc-cpu/src/network/tcp/config.rs
  iris-mpc-cpu/src/network/tcp/data.rs
  iris-mpc-cpu/src/network/tcp/handle.rs
  iris-mpc-cpu/src/network/tcp/mod.rs
  iris-mpc-cpu/src/network/tcp/networking/client.rs
  iris-mpc-cpu/src/network/tcp/networking/connection_builder.rs
  iris-mpc-cpu/src/network/tcp/networking/handshake.rs
  iris-mpc-cpu/src/network/tcp/networking/mod.rs
  iris-mpc-cpu/src/network/tcp/networking/server.rs
  iris-mpc-cpu/src/network/tcp/session.rs
  iris-mpc-cpu/tests/e2e.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
  iris-mpc/src/server/mod.rs
Labels: chore

#1504 Fix processing time and add logs for genesis batches
  iris-mpc-cpu/src/genesis/batch_generator.rs
  iris-mpc-cpu/src/genesis/hawk_job.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
Labels: patch

#1495 Implement table copying for Genesis roll-back
  .github/workflows/temp-branch-build-and-push-upgrade-hawk.yaml
  README.md
  iris-mpc-common/src/server_coordination.rs
  iris-mpc-cpu/src/genesis/state_sync.rs
  iris-mpc-cpu/src/genesis/utils/errors.rs
  iris-mpc-cpu/src/hnsw/graph/graph_store.rs
  iris-mpc-store/src/lib.rs
  iris-mpc-upgrade-hawk/bin/iris_mpc_hawk_genesis.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
Labels: chore

#1505 Only load iris database up to max index id
  .github/workflows/build-all-targets.yml
  .github/workflows/doc.yml
  .github/workflows/lint-clippy.yaml
  iris-mpc-store/src/loader.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
Labels: enhancement

#1506 (bugfix): fix logic that assigns sessions to network connections
  iris-mpc-cpu/src/network/tcp/config.rs
  iris-mpc-cpu/src/network/tcp/handle.rs
Labels: patch
