Repository worldcoin/iris-mpc, pull requests merged in 2025-04, with the labels that each got.

#1220 Fix regression in HNSW algorithm implementation
  iris-mpc-cpu/src/hnsw/searcher.rs
Labels: patch

#1212 [POP-2329] Refactor actor to compute for both normal and mirrored case
  iris-mpc-common/src/helpers/smpc_response.rs
  iris-mpc-common/src/iris_db/iris.rs
  iris-mpc-common/src/job.rs
  iris-mpc-common/src/test.rs
  iris-mpc-cpu/src/execution/hawk_main.rs
  iris-mpc-cpu/tests/e2e.rs
  iris-mpc-gpu/src/dot/distance_comparator.rs
  iris-mpc-gpu/src/dot/kernel.cu
  iris-mpc-gpu/src/server/actor.rs
  iris-mpc-gpu/src/server/mod.rs
  iris-mpc-gpu/tests/e2e.rs
  iris-mpc-store/src/lib.rs
  iris-mpc/bin/server.rs
  iris-mpc/src/services/processors/job.rs
Labels: enhancement

#1242 fix match counters order when reporting results to SNS
  .github/workflows/test-gpu.yaml
  iris-mpc/bin/server.rs
Labels: patch

#1229 calculate bucket statistics for HNSW
  iris-mpc-cpu/src/execution/hawk_main.rs
Labels: enhancement

#1253 Fix: allow CLI input of RNG seeds in init_test_dbs binary
  iris-mpc-cpu/bin/init_test_dbs.rs
Labels: patch

#1251 aurel/refactor-stats: Fix and simplify anon stats
  iris-mpc-cpu/src/execution/hawk_main.rs
Labels: patch

#1265 feat: upgrade AWS OFI NCCL version
  Dockerfile.base
Labels: enhancement

#1267 feat: reduce size of the image
  Dockerfile.base
Labels: enhancement

#1268 feat: upgrade NCCL to latest supported
  Dockerfile.base
Labels: enhancement

#1266 Refactor server_main into smaller function calls
  iris-mpc-common/src/helpers/sync.rs
  iris-mpc/src/server/mod.rs
Labels: chore

#1288 Fix server logging for mirror attack detection in server.rs
  iris-mpc/bin/server.rs
Labels: patch
