Repository worldcoin/iris-mpc, pull requests merged in 2025-01, with the labels that each got.

#882 use fixed chacha seeds for e2e tests
  deploy/e2e/iris-mpc-0.yaml.tpl
  deploy/e2e/iris-mpc-1.yaml.tpl
  deploy/e2e/iris-mpc-2.yaml.tpl
  iris-mpc-common/src/config/mod.rs
  iris-mpc/src/bin/server.rs
Labels: patch

#774 Feat/tls aware reshare protocol
  Cargo.lock
  Dockerfile.nocuda
  deny.toml
  deploy/stage/common-values-reshare-server.yaml
  iris-mpc-upgrade/Cargo.toml
  iris-mpc-upgrade/build.rs
  iris-mpc-upgrade/src/bin/.gitignore
  iris-mpc-upgrade/src/bin/Dockerfile
  iris-mpc-upgrade/src/bin/README.md
  iris-mpc-upgrade/src/bin/aws_local.sh
  iris-mpc-upgrade/src/bin/docker-compose.yaml
  iris-mpc-upgrade/src/bin/nginx/cert/.gitkeep
  iris-mpc-upgrade/src/bin/nginx/cert/server-ext.cnf
  iris-mpc-upgrade/src/bin/nginx/nginx.conf
  iris-mpc-upgrade/src/bin/reshare-client.rs
  iris-mpc-upgrade/src/bin/reshare-server.rs
  iris-mpc-upgrade/src/bin/ssh_chain.sh
  iris-mpc-upgrade/src/bin/tcp_ssl_upgrade_client.rs
  iris-mpc-upgrade/src/config.rs
  iris-mpc-upgrade/src/reshare.rs
  iris-mpc-upgrade/src/utils.rs
Labels: enhancement, chore

#897 Feat: even odd import from s3
  .github/workflows/temp-branch-build-and-push.yaml
  deploy/stage/common-values-iris-mpc.yaml
  deploy/stage/smpcv2-0-stage/values-iris-mpc.yaml
  deploy/stage/smpcv2-1-stage/values-iris-mpc.yaml
  deploy/stage/smpcv2-2-stage/values-iris-mpc.yaml
  iris-mpc-gpu/src/dot/share_db.rs
  iris-mpc-gpu/src/server/actor.rs
  iris-mpc-store/src/lib.rs
  iris-mpc-store/src/s3_importer.rs
  iris-mpc/src/bin/server.rs
Labels: enhancement

#898 Port local copy of HawkSearcher for application-specific customizations
  Cargo.lock
  iris-mpc-cpu/Cargo.toml
  iris-mpc-cpu/benches/hnsw.rs
  iris-mpc-cpu/examples/hnsw-ex.rs
  iris-mpc-cpu/src/hawkers/aby3_store.rs
  iris-mpc-cpu/src/hawkers/plaintext_store.rs
  iris-mpc-cpu/src/hnsw/mod.rs
  iris-mpc-cpu/src/hnsw/searcher.rs
  iris-mpc-cpu/src/lib.rs
  iris-mpc-cpu/src/network/grpc.rs
  iris-mpc-cpu/src/py_bindings/hnsw.rs
  iris-mpc-py/README.md
  iris-mpc-py/examples-py/.gitignore
  iris-mpc-py/examples-py/test_integration.py
  iris-mpc-py/src/py_hnsw/pyclasses/hawk_searcher.rs
  iris-mpc-py/src/py_hnsw/pymodule.rs
Labels: chore

#912 Fix errors in graceful shutdown
  iris-mpc/src/bin/server.rs
Labels: patch

#923 hotfix: Ignore broken batch
  iris-mpc/src/bin/server.rs
Labels: patch

#924 hotfix bump and scale up
  deploy/prod/common-values-iris-mpc.yaml
Labels: patch

#928 hotfix: restore with bump
  deploy/prod/common-values-iris-mpc.yaml
Labels: patch

#936 doc: Provide ADR for load performance optimisation
  adr/002-load-performance-optimisation.md
Labels: chore

#949 Fix creation of gRPC sessions
  iris-mpc-cpu/src/network/grpc.rs
Labels: patch

#957 Debug/e2e tests fix
  iris-mpc-gpu/tests/e2e.rs
Labels: patch

#961 test improvements and debug logging
  Cargo.lock
  iris-mpc-gpu/Cargo.toml
  iris-mpc-gpu/src/dot/distance_comparator.rs
  iris-mpc-gpu/src/dot/kernel.cu
  iris-mpc-gpu/src/server/actor.rs
  iris-mpc-gpu/src/server/mod.rs
  iris-mpc-gpu/tests/e2e.rs
  iris-mpc-gpu/tests/or_policy.rs
Labels: enhancement

#974 [POP-2024] Feat/luc with bitmaps test improvements
  iris-mpc-gpu/tests/e2e.rs
Labels: enhancement

#989 [POP-2073] add buckets as structured response
  .github/workflows/temp-branch-build-and-push.yaml
  Cargo.lock
  deploy/stage/smpcv2-0-stage/values-iris-mpc.yaml
  deploy/stage/smpcv2-1-stage/values-iris-mpc.yaml
  deploy/stage/smpcv2-2-stage/values-iris-mpc.yaml
  iris-mpc-common/Cargo.toml
  iris-mpc-common/src/config/mod.rs
  iris-mpc-common/src/helpers/mod.rs
  iris-mpc-common/src/helpers/smpc_request.rs
  iris-mpc-common/src/helpers/statistics.rs
  iris-mpc-gpu/src/server/actor.rs
  iris-mpc-gpu/src/server/mod.rs
  iris-mpc-gpu/tests/e2e.rs
  iris-mpc/src/bin/server.rs
Labels: enhancement

#993 fix typo
  .github/workflows/test-gpu.yaml
  iris-mpc-common/src/helpers/smpc_request.rs
Labels: patch
