Repository worldcoin/iris-mpc, pull requests merged in 2025-06, with the labels that each got.

#1417 Revise Postgres schemas to represent ids consistently
  iris-mpc-cpu/src/hnsw/graph/graph_store.rs
  migrations/20250530201832_unify_id_repr.down.sql
  migrations/20250530201832_unify_id_repr.up.sql
Labels: enhancement

#1411 Migrate persisted state to the graph store
  .github/workflows/temp-branch-build-and-push-upgrade-hawk.yaml
  iris-mpc-cpu/src/genesis/state_accessor.rs
  iris-mpc-cpu/src/hnsw/graph/graph_store.rs
  iris-mpc-store/src/lib.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
Labels: enhancement

#1430 Hawk Genesis: v0.1.0-rc2
  iris-mpc-common/src/config/mod.rs
  iris-mpc-cpu/src/genesis/batch_generator.rs
  iris-mpc-cpu/src/genesis/hawk_handle.rs
  iris-mpc-cpu/src/genesis/mod.rs
  iris-mpc-cpu/src/genesis/state_accessor.rs
  iris-mpc-cpu/src/genesis/state_sync.rs
  iris-mpc-cpu/src/genesis/utils/errors.rs
  iris-mpc-cpu/src/genesis/utils/mod.rs
  iris-mpc-store/src/lib.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
Labels: enhancement

#1439 fix: only clear anon stat buckets after normal&mirror orientation run
  iris-mpc-gpu/src/server/actor.rs
Labels: patch

#1398 [POP-2478] Store rotation indices for partial matches
  .github/workflows/temp-branch-build-and-push.yaml
  iris-mpc-common/src/helpers/smpc_response.rs
  iris-mpc-common/src/job.rs
  iris-mpc-cpu/src/execution/hawk_main.rs
  iris-mpc-gpu/src/dot/distance_comparator.rs
  iris-mpc-gpu/src/dot/kernel.cu
  iris-mpc-gpu/src/dot/mod.rs
  iris-mpc-gpu/src/server/actor.rs
  iris-mpc-store/src/lib.rs
  iris-mpc/bin/server.rs
  iris-mpc/src/services/processors/job.rs
Labels: enhancement

#1440 Allow suffix for creating GPU database schema
  iris-mpc-common/src/config/mod.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
  iris-mpc/bin/server.rs
  iris-mpc/src/server/mod.rs
Labels: patch

#1438 Fix skip persistence on batch
  .github/workflows/temp-branch-build-and-push-hawk.yaml
  deploy/stage/ampc-hnsw-0-stage/values-ampc-hnsw.yaml
  deploy/stage/ampc-hnsw-1-stage/values-ampc-hnsw.yaml
  deploy/stage/ampc-hnsw-2-stage/values-ampc-hnsw.yaml
  deploy/stage/common-values-ampc-hnsw.yaml
  iris-mpc-cpu/src/execution/hawk_main.rs
  iris-mpc/src/services/processors/batch.rs
  iris-mpc/src/services/processors/job.rs
Labels: patch

#1441 [POP-2563] Genesis: Batch generator unit test hardening
  iris-mpc-cpu/src/genesis/batch_generator.rs
  iris-mpc-cpu/src/genesis/mod.rs
  iris-mpc-cpu/src/genesis/state_accessor.rs
  iris-mpc-cpu/src/genesis/state_sync.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
Labels: enhancement

#1461 [POP-2579] [POP-2578] Chore/remove shadow readonly mode
  .test.env
  .test.hawk0.env
  .test.hawk1.env
  .test.hawk2.env
  deploy/stage/ampc-hnsw-0-stage/values-ampc-hnsw.yaml
  deploy/stage/ampc-hnsw-1-stage/values-ampc-hnsw.yaml
  deploy/stage/ampc-hnsw-2-stage/values-ampc-hnsw.yaml
  docker-compose.dev.yaml
  docker-compose.test.genesis.yaml
  iris-mpc-common/src/config/mod.rs
  iris-mpc-common/src/helpers/sync.rs
  iris-mpc-store/src/lib.rs
  iris-mpc-upgrade-hawk/src/genesis/mod.rs
  iris-mpc/bin/server.rs
  iris-mpc/src/server/mod.rs
  iris-mpc/src/services/processors/batch.rs
  iris-mpc/src/services/processors/job.rs
  scripts/README.md
  scripts/run-server.sh
  scripts/tools/init-db-pgres.sql
  scripts/tools/run-shadowisolation-server.sh
  scripts/tools/run-shadowreadonly-server.sh
Labels: chore
