Repository worldcoin/iris-mpc, pull requests merged in 2025-03, with the labels that each got.

#1093 put modifications behind a feature flag
  .github/workflows/temp-branch-build-and-push.yaml
  Dockerfile
  iris-mpc-common/src/config/mod.rs
  iris-mpc-common/src/helpers/sync.rs
  iris-mpc/bin/server.rs
Labels: patch

#1103 aurel/share-id-0-mini: Fix 1-based party index
  iris-mpc-common/src/galois_engine.rs
  iris-mpc-cpu/src/execution/hawk_main.rs
  iris-mpc-cpu/src/protocol/shared_iris.rs
Labels: patch

#1107 handle empty or rule indices
  deploy/e2e/iris-mpc-0.yaml.tpl
  deploy/e2e/iris-mpc-1.yaml.tpl
  deploy/e2e/iris-mpc-2.yaml.tpl
  iris-mpc/bin/server.rs
  iris-mpc/bin/server_hawk.rs
Labels: patch

#1101 Add e2e client to read from file data
  README.md
  iris-mpc-store/src/lib.rs
  iris-mpc/src/client.rs
  scripts/run-client-docker.sh
  scripts/run-client.sh
Labels: chore

#1109 Fix session creation in gRPC networking
  iris-mpc-cpu/src/network/grpc.rs
Labels: patch

#1104 modularization of iris-mpc-hnsw
  Dockerfile
  Dockerfile.dev.hawk
  Dockerfile.hawk
  README.md
  iris-mpc-gpu/src/helpers/query_processor.rs
  iris-mpc/Cargo.toml
  iris-mpc/bin/client/client.rs
  iris-mpc/bin/server.rs
  iris-mpc/bin/server/iris_mpc_hawk.rs
  iris-mpc/src/client/mod.rs
  iris-mpc/src/lib.rs
  iris-mpc/src/server/mod.rs
  iris-mpc/src/server/utils.rs
  iris-mpc/src/services/aws/clients.rs
  iris-mpc/src/services/aws/mod.rs
  iris-mpc/src/services/aws/s3.rs
  iris-mpc/src/services/aws/sns.rs
  iris-mpc/src/services/init/mod.rs
  iris-mpc/src/services/mod.rs
  iris-mpc/src/services/processors/batch.rs
  iris-mpc/src/services/processors/mod.rs
  iris-mpc/src/services/store/mod.rs
  scripts/run-server-docker.sh
  scripts/run-server.sh
Labels: chore

#1113 fix failing check
  Cargo.lock
  deny.toml
Labels: patch

#1115 aurel/fix-left-rotated: Fix left/right typo
  iris-mpc/src/services/processors/batch.rs
Labels: patch

#1114 Add running of entire e2e data set
  .test.env
  README.md
  iris-mpc/bin/client/client.rs
  iris-mpc/src/client/e2e.rs
  iris-mpc/src/client/iris_data.rs
  iris-mpc/src/client/mod.rs
  scripts/run-client-docker.sh
  scripts/run-client.sh
Labels: chore

#1136 Add purging scripts for HNSW in staging
  scripts/purge_stage/README.md
  scripts/purge_stage/accounts_checker.sh
  scripts/purge_stage/db-cleaner-helper-pod.yaml
  scripts/purge_stage/delete_mongodb_cpu_collections.sh
  scripts/purge_stage/delete_mongodb_gpu_collections.sh
  scripts/purge_stage/purge_stage_dbs.sh
  scripts/purge_stage/purge_stage_mongo_collections.sh
  scripts/purge_stage/purge_stage_queues.sh
  scripts/purge_stage_dbs.sh
  scripts/purge_stage_mongo_collections.sh
  scripts/purge_stage_queues.sh
Labels: chore

#1155 aurel/fix-split-tasks: Fix split tasks
  iris-mpc-cpu/src/execution/hawk_main/is_match_batch.rs
Labels: patch

#1161 Rust toolchain upgrade
  .github/workflows/build-all-targets.yml
  .github/workflows/check-licenses.yaml
  .github/workflows/doc.yml
  .github/workflows/lint-clippy.yaml
  .github/workflows/lint-rustfmt.yaml
  .github/workflows/run-unit-tests.yaml
  .github/workflows/test-gpu.yaml
  Cargo.lock
  Dockerfile
  Dockerfile.debug
  Dockerfile.dev.hawk
  Dockerfile.hawk
  Dockerfile.nocuda
  Dockerfile.reshare-protocol
  Dockerfile.shares-encoding
  iris-mpc-cpu/src/execution/hawk_main.rs
  iris-mpc-cpu/src/shares/vecshare.rs
  iris-mpc-gpu/benches/transpose.rs
  iris-mpc-gpu/src/helpers/comm.rs
  iris-mpc-gpu/src/threshold_ring/protocol.rs
  iris-mpc-gpu/tests/bucket_threshold.rs
  iris-mpc-gpu/tests/buckets.rs
  iris-mpc-gpu/tests/extract_msb_mod.rs
  iris-mpc-gpu/tests/one_bucket.rs
  iris-mpc-gpu/tests/threshold.rs
  iris-mpc-gpu/tests/threshold_and_or_tree.rs
  iris-mpc-py/Cargo.toml
  iris-mpc-py/src/py_hnsw/pyclasses/graph_store.rs
  iris-mpc-py/src/py_hnsw/pyclasses/iris_code.rs
  iris-mpc/bin/server.rs
  iris-mpc/src/services/store/mod.rs
  rust-toolchain.toml
Labels: enhancement

#1154 Fix purge stage dbs script
  scripts/purge_stage/db-cleaner-helper-pod-ampc-hnsw.yaml
  scripts/purge_stage/db-cleaner-helper-pod-iris-mpc.yaml
  scripts/purge_stage/delete_mongodb_cpu_collections.sh
  scripts/purge_stage/delete_mongodb_gpu_collections.sh
  scripts/purge_stage/purge_stage_dbs.sh
Labels: patch

#1159 Implement parallel MPC execution for HNSW graph insertion
  iris-mpc-cpu/src/hnsw/graph/neighborhood.rs
  iris-mpc-cpu/src/hnsw/searcher.rs
  iris-mpc-cpu/src/hnsw/sorting/binary_search.rs
  iris-mpc-cpu/src/hnsw/sorting/mod.rs
Labels: enhancement

#1179 multiple cleanups
  .env.mpc1.dist
  .env.mpc2.dist
  .env.mpc3.dist
  .envrc.example
  .github/workflows/build-and-push-nccl.yaml
  .github/workflows/build-and-push-no-cuda.yaml
  .github/workflows/build-and-push-shares-encoding.yaml
  Dockerfile.nocuda
  README.md
Labels: chore

#1187 [POP-2328] Enrich BatchQuery with mirrored shares and masks for mirror attack detection
  iris-mpc-common/src/job.rs
  iris-mpc/bin/server.rs
Labels: enhancement

#1191 fix warning in doctests
  iris-mpc-gpu/src/helpers/comm.rs
Labels: patch

#1184 Parallel prefix adder to extract MSB in less-than operation
  iris-mpc-cpu/src/protocol/binary.rs
Labels: patch
